site_name: Cloud Workshop
site_description: Azure Cloud Workshop Documentation
site_author: 40docs
site_url: https://40docs.github.io/workshop_azure/
copyright: "40docs Organization"

# Repository
repo_name: 40docs/workshop_azure
repo_url: https://github.com/40docs/workshop_azure

# Navigation
nav:
  - Home: index.md
  - Getting Started: getting-started.md

# Theme configuration
theme:
  name: material
  custom_dir: theme
  logo: fabric.svg
  logo_dark: fabric-white.svg
  favicon: favicon.ico
  font:
    text: Inter
    code: Roboto Mono
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

# Markdown extensions
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

# Plugins
plugins:
  - search
  - glightbox:
      zoomable: true

# Extra CSS and JavaScript
extra_css:
  - extra.css

extra_javascript:
  - custom.js

# Social links
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/40docs